"use client";

import { useState, useSyncExternalStore } from "react";
import { useRouter } from "next/navigation";
import { PageContainer } from "@/components/PageContainer";
import { Card } from "@/components/Card";
import { Button } from "@/components/Button";
import { Badge } from "@/components/Badge";
import { Alert } from "@/components/Alert";
import { ProgressBar } from "@/components/ProgressBar";
import { EmptyState } from "@/components/EmptyState";
import { AppHeader } from "@/components/AppHeader";
import { scoreQuiz } from "@/lib/quizScoring";
import {
  getServerStorageSnapshot,
  readQuiz,
  RESULT_STORAGE_KEY,
  subscribeToStorage,
} from "@/lib/storage";
import type { UserAnswer } from "@/lib/types";

const letters = ["A", "B", "C", "D"];

export default function QuizPage() {
  const router = useRouter();
  const quiz = useSyncExternalStore(subscribeToStorage, readQuiz, getServerStorageSnapshot);
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [answers, setAnswers] = useState<UserAnswer[]>([]);

  if (!quiz || !quiz.questions[index]) {
    return (
      <>
        <AppHeader />
        <EmptyState message="没有找到可用的测验，请先生成题目。" />
      </>
    );
  }

  const question = quiz.questions[index];
  const isCorrect = selected === question.answer;
  const isLast = index === quiz.questions.length - 1;

  function submit() {
    if (!selected || submitted) return;
    setAnswers((current) => [
      ...current,
      { questionId: question.id, selectedAnswer: selected, isCorrect },
    ]);
    setSubmitted(true);
  }

  function next() {
    if (!submitted) return;
    if (isLast) {
      const result = scoreQuiz(quiz!, answers);
      localStorage.setItem(RESULT_STORAGE_KEY, JSON.stringify(result));
      router.push("/result");
      return;
    }
    setIndex((current) => current + 1);
    setSelected("");
    setSubmitted(false);
  }

  return (
    <>
      <AppHeader />
      <PageContainer maxWidth="md">
        {/* Header */}
        <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <Badge variant="cyan" size="sm" className="mb-2">
              Generated by DeepSeek API
            </Badge>
            <h1 className="text-2xl font-bold text-white">{quiz.topic}</h1>
          </div>
          <p className="text-sm text-slate-400 shrink-0">
            {index + 1} / {quiz.questions.length}
          </p>
        </div>

        <ProgressBar
          value={index + 1}
          max={quiz.questions.length}
          className="mb-6"
        />

        {/* Question Card */}
        <Card padding="lg">
          {/* Meta badges */}
          <div className="mb-5 flex flex-wrap gap-2">
            <Badge variant="neutral" size="sm">
              {question.difficulty}
            </Badge>
            {question.knowledgePoints.map((point) => (
              <Badge key={point} variant="cyan" size="sm">
                {point}
              </Badge>
            ))}
          </div>

          <h2 className="text-xl font-bold leading-8 text-white sm:text-2xl">
            {question.question}
          </h2>

          {/* Options */}
          <div className="mt-7 space-y-3">
            {question.options.map((option, optionIndex) => {
              const active = selected === option;
              const correct = submitted && option === question.answer;
              const wrong = submitted && active && !correct;

              let stateClass = "border-[var(--color-border)] bg-[var(--color-bg-surface)] text-[var(--color-text-secondary)] hover:border-[var(--color-border-hover)]";
              if (correct) {
                stateClass = "border-[var(--color-success)] bg-[var(--color-success-bg)] text-[var(--color-success-text)]";
              } else if (wrong) {
                stateClass = "border-[var(--color-danger)] bg-[var(--color-danger-bg)] text-[var(--color-danger-text)]";
              } else if (active) {
                stateClass = "border-[var(--color-primary)] bg-[var(--color-primary-bg)] text-white";
              }

              return (
                <button
                  key={option}
                  type="button"
                  disabled={submitted}
                  onClick={() => setSelected(option)}
                  className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition ${stateClass}`}
                >
                  <span className="grid size-8 shrink-0 place-items-center rounded-lg bg-white/5 text-sm font-bold">
                    {letters[optionIndex]}
                  </span>
                  {option}
                </button>
              );
            })}
          </div>

          {/* Feedback */}
          {submitted && (
            <Alert
              variant={isCorrect ? "success" : "error"}
              title={isCorrect ? "回答正确" : `回答错误，正确答案：${question.answer}`}
              className="mt-7"
            >
              <p className="mt-1">{question.explanation}</p>
              <p className="mt-2 text-sm opacity-80">来源：{question.source}</p>
            </Alert>
          )}

          {/* Action button */}
          <div className="mt-7 flex justify-end">
            {!submitted ? (
              <Button variant="primary" disabled={!selected} onClick={submit}>
                提交答案
              </Button>
            ) : (
              <Button variant="primary" onClick={next}>
                {isLast ? "查看结果" : "下一题"}
              </Button>
            )}
          </div>
        </Card>
      </PageContainer>
    </>
  );
}
